FROM ubuntu:18.04

# install required software
RUN apt-get update --fix-missing && apt-get install -y curl git dnsutils net-tools wget

# setup folder structure
RUN mkdir /eosio
RUN mkdir /eosio/build
RUN mkdir /eosio/downloads

# setup build time variables
ARG NODEOS_REPOSITORY
ENV NODEOS_REPOSITORY $NODEOS_REPOSITORY
ARG NODEOS_VERSION
ENV NODEOS_VERSION $NODEOS_VERSION

# build nodeos
WORKDIR /eosio/build
RUN git clone -b $NODEOS_VERSION $NODEOS_REPOSITORY /eosio/build
RUN git submodule update --init --recursive
RUN apt-get update --fix-missing
RUN ./scripts/install_deps.sh && ./scripts/pinned_build.sh /eosio/deps /eosio/build/build $(nproc)
RUN cp /eosio/build/build/programs/nodeos/nodeos /eosio/nodeos
RUN rm -rf /eosio/build/build /eosio/build/deps

# configure nodeos
COPY configs/config.ini /eosio/base.ini

# copy startup script
COPY scripts/entrypoint-minimal-api.sh /eosio/entrypoint.sh
RUN chmod +x /eosio/entrypoint.sh

# DEBUG: copy snapshot from local into build to prevent redownloading
# COPY downloads/latest.tar.gz /eosio/downloads/snapshot.tar.gz

# start nodeos
WORKDIR /eosio
CMD ["/eosio/entrypoint.sh"]
