FROM ubuntu:20.04

# install required software
RUN apt-get update --fix-missing && DEBIAN_FRONTEND=noninteractive apt-get install -y curl \
    git \
    dnsutils \
    net-tools \
    build-essential \
    cmake \
    git \
    libcurl4-openssl-dev \
    libgmp-dev \
    llvm-11-dev \
    python3-numpy \
    file \
    zlib1g-dev \
    g++-10
# setup folder structure
RUN mkdir /eosio
RUN mkdir /eosio/build
RUN mkdir /eosio/downloads

# setup build time variables
ARG NODEOS_REPOSITORY
ENV NODEOS_REPOSITORY $NODEOS_REPOSITORY
ARG NODEOS_VERSION
ENV NODEOS_VERSION $NODEOS_VERSION

# build nodeos
WORKDIR /eosio/build
RUN git clone -b $NODEOS_VERSION $NODEOS_REPOSITORY /eosio/build
RUN git submodule update --init --recursive
RUN mkdir -p build
WORKDIR /eosio/build/build
RUN cmake -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-11 ..
RUN make -j "$(nproc)" nodeos
RUN cp /eosio/build/build/programs/nodeos/nodeos /eosio/nodeos
RUN rm -rf /eosio/build/build

# configure nodeos
COPY configs/config.ini /eosio/base.ini

# copy example logging, and potentially overwrite with a logging.json in the configs directory
COPY configs/nodeos/default-logging.json /eosio/logging.json
COPY README.md configs/*logging.json /eosio/

# copy startup script
COPY scripts/entrypoint-minimal-api.sh /eosio/entrypoint.sh
RUN chmod +x /eosio/entrypoint.sh

# start nodeos
WORKDIR /eosio
CMD ["/eosio/entrypoint.sh"]
