version: '3.6'
services:
    nodeos:
        build: 
            context: .
            args:
                - NODEOS_REPOSITORY=${NODEOS_REPOSITORY}
                - NODEOS_VERSION=${NODEOS_VERSION}
        env_file:
            - .env
        expose: [8888]
        labels:
            - traefik.enable=true
            - traefik.http.routers.nodeos.rule=Host(`nodeos.docker.localhost`)
            - traefik.http.services.nodeos.loadbalancer.server.port=8888
        tmpfs:
            - /ramdisk:defaults,nosuid,nodev,noatime,nodiratime,exec,size=64G
    traefik:
        image: "traefik:v2.4"
        command:
            - "--accesslog"
            - "--accesslog.filepath=/var/log/traefik/access.log"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "./traefik:/var/log/traefik"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            