FROM ubuntu:20.04

# install required software
RUN apt-get update --fix-missing && DEBIAN_FRONTEND=noninteractive apt-get install -y curl git dnsutils net-tools

# setup folder structure
RUN mkdir /eosio
RUN mkdir /eosio/build
RUN mkdir /eosio/downloads
RUN mkdir /eosio/patches

# setup build time variables
ARG NODEOS_REPOSITORY
ENV NODEOS_REPOSITORY $NODEOS_REPOSITORY
ARG NODEOS_VERSION
ENV NODEOS_VERSION $NODEOS_VERSION

# fetch nodeos
WORKDIR /eosio/build
RUN git clone -b $NODEOS_VERSION $NODEOS_REPOSITORY /eosio/build
RUN git submodule update --init --recursive
# apply any patches in the shared/patches folder
COPY shared/patches /eosio/patches
RUN git apply /eosio/patches/*.diff || true
RUN git apply /eosio/patches/*.patch || true
# build nodeos
RUN ./scripts/install_deps.sh && ./scripts/pinned_build.sh /eosio/deps /eosio/build/build $(nproc)
RUN cp /eosio/build/build/programs/nodeos/nodeos /eosio/nodeos
RUN rm -rf /eosio/build/build /eosio/build/deps

# configure nodeos
COPY configs/config.ini /eosio/base.ini

# copy example logging, and potentially overwrite with a logging.json in the configs directory
COPY configs/nodeos/default-logging.json /eosio/logging.json
COPY README.md configs/*logging.json /eosio/

# copy startup script
COPY scripts/entrypoint-minimal-p2p.sh /eosio/entrypoint.sh
RUN chmod +x /eosio/entrypoint.sh

# start nodeos
WORKDIR /eosio
CMD ["/eosio/entrypoint.sh"]
