version: '3.6'
services:
    nodeos:
        build: 
            dockerfile: Dockerfile-minimal-api
        extends:
            file: ./nodeos-minimal-base.yaml
            service: nodeos
        volumes:
            - ../../shared:/eosio/shared
