version: '3.6'
services:
    nodeos:
        build: 
            dockerfile: Dockerfile-minimal-p2p
        extends:
            file: ./nodeos-minimal-base.yaml
            service: nodeos
        ports:
            - 9876:9876 # expose p2p port
